remote_theme: chrisrhymes/bulma-clean-theme

title: Libraries hacked
tagline: Promoting open data and hacks in libraries
email: info@librarieshacked.org
description: Promoting open data and hacks in libraries
baseurl: "/"
url: "https://www.librarieshacked.org"
permalink: pretty

paginate: 5
paginate_path: "/blog/page:num"

disqus:
  shortname: 

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true

markdown: kramdown
highlighter: rouge

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
