# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Set plugins
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji
  - jekyll-remote-theme

author: DaveBathnes
social:
  name: Libraries Hacked
  links:
    - https://www.instagram.com/librarieshacked
    - https://www.linkedin.com/in/rowedave
    - https://github.com/librarieshacked

# Site settings
url: 'https://www.librarieshacked.org'
baseurl: ''
title: 'Libraries Hacked'
description: 'Promoting open data and digital prototypes in libraries'
permalink: pretty
logo: '/assets/images/logo_small.png'
repo: 'https://github.com/davebathnes/librarieshacked'
email: 'info@librarieshacked.org'

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Projects
    url: /projects/

# Collection settings
defaults:
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: page # Set the default layout for pages

navigation_footer:
  - title: Created by Libraries Hacked
    url: https://www.librarieshacked.org

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/LibrariesHacked
  LinkedIn: https://www.linkedin.com/in/rowedave
  GitHub: https://github.com/librarieshacked
  RSS: https://blog.librarydata.uk/feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: '#0d94e7'
  facebook: '#3B5998'
  Email: true

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap

service_worker: false
